### ISSUE TITLE
continueTestingAfterFailure does not work as expected

### ISSUE THREAD

**Issue by TemperMichael** [Tyler-Keith-Thompson/CucumberSwift#24] opened 2021-02-03 15:13 UTC
Hey, first of all, thanks for this up to date Pod!

I am rather new to testing, especially with cucumber, and encountered some problems with failing tests. First of all, something minor I noticed: empty steps are shown as successful tests, is that on purpose?

Anyway, I failed all empty tests explicitly with XCTFail("Not implemented yet") and even though continueTestingAfterFailure is set to false, the tests still continue when a test failed. I looked up the code a bit and it seems the continueTestingAfterFailure / continueAfterFailure values are set, but actually are nowhere checked, is that possible? Maybe I also just overlooked something.

Furthermore, I wanted to ask if it is somehow possible to run single tests once they have been run at least once? As far as I understood, the test cases are generated out of the scenarios. Afterwards they are all shown in the test navigator, but I cannot run them as single tests.

**To Reproduce**
1. Set continueTestingAfterFailure in the StepImplementation to false. 
2. Run a test with multiple scenarios where one of them fails.
3. See that the testing still continues after one of them failed.

**Expected behavior**
The tests stop as soon as one of them fails.

**Additional context**
 - XCode Version: 12.3
 - CucumberSwift Version: 3.1.1

**Comment by Tyler-Keith-Thompson** [comment] 2021-02-04 01:03
Let's start with empty step definitions not throwing an error. This is on purpose. Because Gherkin can be used so expressively to communicate intent every once in a while a step doesn't actually need to execute code. Using `XCTFail("Not Implemented")` is a perfect solution if that's your desired behavior. Also note you can identify steps that don't have any code associated by looking for the generated step stubs file, if it's not there then all steps are accounted for.

As far as continueTestingAfterFailure I was not able to reproduce your issue. You might be being tricked by Xcode's test navigator if you ran all the tests *before* you added the `continueTestingAfterFailure` configuration. A clean might resolve it. Here's a screenshot I took (admittedly using Xcode 12.4) to prove this out.

<img width="2164" alt="Screen Shot 2021-02-03 at 5 49 45 PM" src="https://user-images.githubusercontent.com/33705774/106829208-ec1e0180-6648-11eb-83c0-f93009eda89e.png">

You'll notice the test failed, but the fatalError was never triggered, because they don't continue after failure.


Now as far as rerunning tests. Apple does not make it remotely easy to actually tie into Xcode features. Nothing is clearly documented. I'll try to dive into this a little bit and see if there's *something* I can do to pick up on the fact you want to rerun a dynamically generated test.

However here are a couple of workarounds:
```swift
extension CucumberSwift: StepImplementation {
    public func shouldRunWith(scenario: Scenario?, tags: [String]) -> Bool {
        //return shouldRun(scenario?.withLine(4)) // NOTE: The line number here should represent the line in your feature file
        //return scenario?.tags.contains("run") == true // Anything tagged with "run" is executed, but nothing else. Also see the == true is because scenario? turns our boolean into an optional so this comparison is necessary
        //return scenario?.title == "Scenario you want"
        //return scenario?.feature?.title == "Feature you want" // You can access the feature like this, it has all the same capabilities as listed above
        return true // obviously this runs everything, same as if you simply don't have this method
    }
}
```

**Comment by TemperMichael** [comment] 2021-02-04 12:56
Thanks for your fast response!

Ah I think it's a miss-understanding from my side - so `continueTestingAfterFailure ` stops the current Scenario test and not the testing overall? Since I think the single scenarios get stopped as in your screenshot - but the overall testing continues.

Ah nice, the workarounds will definitely already make testing easier 😄 thanks!

**Comment by Tyler-Keith-Thompson** [comment] 2021-02-04 14:51
Ahh! Yes. The documentation could at least be more clear about that. Because every scenario is considered not a test, but a test case. The thought is that each scenario should always be independently executable because you can't necessarily guarantee run order in a Cucumber implementation.

Anyways this is great for things like parallelization but I can see how that'd be confusing. I'll update the docs before closing the issue and create a card to see if I can tie into the test navigator's rerun a bit better.

**Comment by TemperMichael** [comment] 2021-02-04 15:07
Sounds good - thanks for your help! 🙂 👍

**Closed** 2021-02-04 15:40 UTC
Labels: help wanted
