### ISSUE TITLE
Feature including scenario outline is not executed if features are filtered by tag and target tag is placed above 'Feature' keyword

### ISSUE THREAD

**Issue by olyv** [Tyler-Keith-Thompson/CucumberSwift#6] opened 2019-08-09 07:27 UTC
**Describe the bug**
Feature including scenario outline is not executed if features are filtered by tag and target tag is placed above 'Feature' keyword

**To Reproduce**
1. Create feature file with some content like 
```
@1234567
Feature: Minimal Scenario Outline

Scenario Outline: minimalistic
Given the <what>

Examples:
| what       |
| minimalism |
```
2. Specify tagged feature 
```
public func shouldRunWith(tags: [String]) -> Bool {
      return tags.contains("1234567")
}
```
3. Execute tests

**Expected behavior**
`Minimal Scenario Outline` is executed (or step definitions are generated in case of missing step definitions)

**Actual behavior**
No tests found to execute, step definitions are not generated

**Additional context**
 - XCode Version: XCode 10.2.1
 - CucumberSwift Version: 2.2.3

Please note, that feature is executed if tag is moved above `Scenario Outline` keyword
```
Feature: Minimal Scenario Outline

@1234567
Scenario Outline: minimalistic
Given the <what>

Examples:
| what       |
| minimalism |
```

**Comment by Tyler-Keith-Thompson** [comment] 2019-08-18 21:02
I suspect v2.2.4 fixes this as well, but because I don't have a *specific* test in place for this issue I won't close it until I verify it has been fixed. Give me a little while to get a test in place, but in the meantime give 2.2.4 a try.

**Comment by Tyler-Keith-Thompson** [comment] 2019-08-19 02:44
Confirmed, but with a test added to prevent future regression :)

**Closed by Tyler-Keith-Thompson** 2019-08-19 02:44 UTC
